Centered collapsible with a fixed width
SimplQ/simplQ-frontend pull request #192
Opened 2020-08-23 16:43 UTC by jithinlal

2020-08-23 17:20 UTC, daltonfury42 commented
Please keep updating the same PR. It's a bit difficult to review when you keep opening new PRs.

2020-08-23 19:20 UTC, maaverik commented
It crashes for me too when I click the button. Also, styling has to be done later on. @jithinlal, could you merge the latest code and try to recreate the problem?

![Screenshot from 2020-08-24 00-47-25](https://user-images.githubusercontent.com/12583528/90986841-8874b000-e5a3-11ea-9c8e-65129b7fed9f.png)

![Screenshot from 2020-08-24 00-49-46](https://user-images.githubusercontent.com/12583528/90986860-c1148980-e5a3-11ea-9329-aa9a7befb14f.png)

2020-08-25 20:32 UTC, maaverik commented
@daltonfury42  could you take a look at this when you get some time? It's something to do with the joinQueuHandler being passed incorrectly to the joinForm component. I looked at it for a while but I can't figure out what's wrong.

2020-08-25 20:42 UTC, maaverik commented
Got it. I was looking at the wrong place. In /components/pages/Admin/index.jsx, in addNewItem, nothing's being returned. This function is being passed into the joinQueueHandler in Form.jsx. Adding a return there fixes it.

  const addNewItem = (name, contactNumber) => {
```
    return TokenService.create(name, contactNumber, false, queueId)
      .then((response) => {
        setItems([
```

2020-08-29 05:32 UTC, daltonfury42 requested changes

2020-08-29 05:32 UTC, daltonfury42 commented on simplq/src/components/common/Collapsible/Collapsible.jsx
> +            <AddIcon />
Can we also pass down the icon as a prop?

2020-08-29 09:07 UTC, jithinlal commented
Hi,
Is this PR still open?

2020-08-29 10:13 UTC, daltonfury42 commented
Yes

2020-10-03 20:43 UTC, maaverik commented
Closing because this page has been redesigned.

2020-10-03 20:43 UTC, closed without merging